services:

  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    image: Front_image
    ports:
      - 9000:9000
    depends_on:
      - backend

  
  backend:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    image: Back-image
    ports:
      - 5252:5252